from __future__ import annotations
import json
import os
import re
import shutil
import socket
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from .model import Frame
from .collectors import clean
ROTATION_SCRIPT_NAME = "lcd-rotation.script"
CHANNELS_NAME = "lcd-channels.lck"
STATUS_NAME = "lcd-system-info.json"

def render_rotation_script(frames: list[Frame]) -> str:
    lines = [
        "# Generated by lcd-system-info-publisher.",
        f"# Updated {datetime.now(timezone.utc).isoformat()}",
    ]
    for frame in frames:
        lines.append(f'# {frame.key}')
        lines.append(f'frame "{quote_frame_line(frame.line1)}" "{quote_frame_line(frame.line2)}"')
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{os.getpid()}")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def publish(lock_dir: Path, *, frames: list[Frame], dry_run: bool = False) -> list[Frame]:
    if dry_run:
        return frames
    atomic_write(lock_dir / ROTATION_SCRIPT_NAME, render_rotation_script(frames))
    atomic_write(lock_dir / CHANNELS_NAME, "script\n")
    atomic_write(
        lock_dir / STATUS_NAME,
        json.dumps(
            {
                "updated_at": datetime.now(timezone.utc).isoformat(),
                "frame_count": len(frames),
                "frames": [frame.__dict__ for frame in frames],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )
    return frames


