"""LCD hardware device ownership and minimal shared device interface."""
from __future__ import annotations
from typing import Protocol

class LCDDevice(Protocol):
    def init_lcd(self) -> None: ...
    def write_frame(self, line1: str, line2: str) -> None: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
